### ISSUE TITLE
Feature Request: Move completed tasks to bottom in plain text mode

### ISSUE THREAD

**Issue by wireddude** [sn-extensions/simple-task-editor#1]
I often switch between mobile (plain text view" and the task-editor view on my desktop. when viewing on mobile, all my "done" tasks show up at the top of the plaintext view. Can they be moved below the "to do" section so they don't show up first at the top of mobile?

**Comment by mobitar** [comment]
That's a good point. I'll make this change for the next release.

**Comment by wireddude** [comment]
works really well!
