### ISSUE TITLE
Feature-request: Allow re-ordering of items

### ISSUE THREAD

**Issue by thomaseizinger** [sn-extensions/simple-task-editor#11]
Currently, it is not possible to change the order of the items after they are added.

However, it would be very useful to be able to so for expressing things like priority. I've got a long-lasting "TODO" list that I continuously extend with new items as well as complete existing ones. However, it is a bit cumbersome this way because I cannot express which ones I want to do next.

Being able to re-order them would greatly help with that!

**Comment by thomaseizinger** [comment]
I just noticed that this does work on the Desktop and just not on mobile! Maybe it is a bug-report then and not a feature-request? :)

**Comment by mobitar** [comment]
Yes indeed, you can re-order on desktop, but on mobile, the gesture is just a little difficult to make work. But for sure, if we can get it to work, we'd get this same feature on mobile.

**Comment by ivywong** [comment]
It looks like this is possible in the Android app (v3.0.10) if you press and hold on the checkbox and drag the item to where you want it to be.

**Comment by thomaseizinger** [comment]
Works indeed!
Had to reinstall the app (although deleting cache might have done it aswell) to get the new editor version!
Thanks @dagjaneiro!
