### ISSUE TITLE
On iOS, "Clear Completed" does not present the usual confirmation alert, and has no action

### ISSUE THREAD

**Issue by mobitar** [sn-extensions/simple-task-editor#15]

**Comment by frvkl** [comment]
Same Issue. Href seems to be blocked in Simple Markdown Editor too?

**Comment by mobitar** [comment]
@frvkl good point. Hadn't noticed this. Will need to investigate.

**Comment by mobitar** [comment]
Both of these issues will be fixed by the upcoming mobile app update (3.0.6).

**Comment by frvkl** [comment]
I had to update my self hosted Simple Markdown Editor, but it is fixed now. Thank You!
