### ISSUE TITLE
Meta viewport missing

### ISSUE THREAD

**Issue by daniele-athome** [sn-extensions/simple-task-editor#18]
I noticed that index.html is missing the meta viewport tag:

```
<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1">
```

Resulting in something like standardnotes/mobile#156.
I noticed that other extensions don't have the meta tag as well. However, [your staging code for the demo instance has it](https://extensions.standardnotes.org/staging-demos/components/simple-task-editor?type=component&area=editor-editor&name=Simple%20Task%20Editor). Is your source code here kept up-to-date to the actual source code?

**Comment by mobitar** [comment]
For our hosted extensions we use a custom index.html for all extensions, which does contain the viewport tag. But, I suppose it would be worth adding to the source as well, for offline extensions, if [that feature](https://github.com/standardnotes/bounties/issues/29) ever does make its way to mobile.

**Comment by daniele-athome** [comment]
>  But, I suppose it would be worth adding to the source as well, for offline extensions

Well, I have some extensions hosted on my own server and the viewport tag would be useful also for that too (If I understood your point correctly).

**Comment by mobitar** [comment]
Good point, I'll queue these updates. Thanks for offering to help; I think the changes are trivial so it would be easier to manage them myself than to go the PR route.

**Comment by kylejbrk** [comment]
Is there an update on this?

**Comment by mobitar** [comment]
Yup, this is fixed.
