### ISSUE TITLE
[BUG] Overwrites lists when switching

### ISSUE THREAD

**Issue by Stk2329** [sn-extensions/simple-task-editor#19]
### Specs:
OS: Linux Ubuntu 18.04
SN Version: 3.0.9
Simple Task Version: 1.3.2

### Description
Sometimes if I switch between two _Simple Task_ lists one of the lists is overwritten by the other. So both are then the same. It rarely happens (roughly twice in the last couple of month).

However, it is possible to fix this by using the _Session History_. See screenshot.
![example](https://user-images.githubusercontent.com/33157936/59039865-e8cfe280-8875-11e9-9a8a-72d917128983.png)

**Comment by mobitar** [comment]
Oo interesting. I was able to replicate this by making a change to one note then quickly switching to the next note before the first has a chance to finish saving. I'll investigate a fix for the next release. Thanks!

**Comment by mobitar** [comment]
This issue should now be fixed, and requires all editors to be updated from the Extensions menu.
