### ISSUE TITLE
dist.js and dist.css dist.css.map location

### ISSUE THREAD

**Issue by BobTB** [sn-extensions/simple-task-editor#2]
When self hosting it looks for dist.js, dist.css.map and dist.css in the same path as the index.html is, therefore for it to work I had to move the files from dist folder to the editors root folder

**Comment by mobitar** [comment]
Right, the index.html is in the same folder as the other files: https://github.com/sn-extensions/simple-task-editor/tree/master/dist

This might be different from some of the other components, but that's because this uses a different framework and build system.
