### ISSUE TITLE
Delete task / auto-delete empty tasks

### ISSUE THREAD

**Issue by jceb** [sn-extensions/simple-task-editor#20]
Is there a way to delete a task? I've seen the code for delete task but it seems not to be used. I'd appreciate a button to delete individual tasks rather than having to clear them all.

A workaround would be to have an auto-delete for empty tasks. This I'm truly missing since my workflow includes copying tasks from one document to another via cut & paste. This leaves lots of empty tasks that are very difficult to get rid of.

**Comment by mobitar** [comment]
Yes, if you clear the text from a task, then press enter, it will delete.

**Comment by jceb** [comment]
Awesome, thank you for the missing peace of information!
