### ISSUE TITLE
Documentation for local development and contributions

### ISSUE THREAD

**Issue by ruppalsingh** [sn-extensions/simple-task-editor#4]
I'm interesting in contributing to the project.

Any thoughts on a `README.md` detailing how to get started with local development and consequently any guidelines on working on new features?

**Comment by mobitar** [comment]
Hey @ruppalsingh, thanks for wanting to help out. We have some docs available here: docs.standardnotes.org. In general, we mostly want to avoid new features when it comes to pull requests, and instead only focus on bug fixes.
